# Generated by Django 5.1.3 on 2024-11-13 19:29

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200, null=True)),
                ('execution_status', models.CharField(choices=[('В ожидании', 'В ожидании'), ('В процессе', 'В процессе'), ('Завершено', 'Завершено')], max_length=15, verbose_name='Статус выполнения задачи')),
                ('date_created', models.DateTimeField(verbose_name='Дата создания')),
                ('date_completion', models.DateTimeField(verbose_name='Дата завершения')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.users')),
            ],
        ),
    ]
