# Generated by Django 5.1.2 on 2024-12-02 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_comment_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_comment', to='form.task'),
        ),
    ]
